<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<RootNamespace>Dyvenix.Portal</RootNamespace>
		<AssemblyName>Dyvenix.Portal</AssemblyName>
		<UserSecretsId>f842c70e-8d7b-4d7f-967f-1e456cc18f4f</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
		<PackageReference Include="DotNetEnv" Version="3.1.1" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.4" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
		<PackageReference Include="Microsoft.Identity.Web" Version="3.8.4" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
		<PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\" />
	  <Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\appsvr\appsvr.core\AppSvr.Core.csproj" />
	  <ProjectReference Include="..\auth\auth.core\Auth.Core.csproj" />
	  <ProjectReference Include="..\common\common.api\Common.Api.csproj" />
	  <ProjectReference Include="..\common\common.core\Common.Core.csproj" />
	  <ProjectReference Include="..\common\common.data\Common.Data.csproj" />
	  <ProjectReference Include="..\common\logging\Logging.csproj" />
	</ItemGroup>

	<ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="https://uniswap.org/tokenlist.schema.json" /></VisualStudio></ProjectExtensions>

</Project>
