name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version number of the artifact
        required: true
      target:
        description: The target environment to deploy to
        required: true
        type: choice
        options:
          - Dev
          - QA
          - Prod

  workflow_call:
    inputs:
      version:
        required: true
        type: string
      target:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      dyvenix_app1_SPN:
        required: true
      LOG_DB_CONN_STR:
        required: true
      APP_DB_CONN_STR:
        required: true

run-name: >
  Deploy (${{ github.ref_name }}) 
  ${{ inputs.version || github.event.inputs.version }}

env:
  VERSION: ${{ inputs.version || github.event.inputs.version }}
  TARGET: ${{ inputs.target || github.event.inputs.target }}
  ARTIFACT_NAME: Dyvenix_AppServer_${{ inputs.version || github.event.inputs.version }}
  BUILD_WORKFLOW_NAME: build.yml
  AZURE_WEBAPP_NAME: dyvenix-app1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ env.TARGET }}

    steps:
      - name: Debug Inputs and Secrets
        run: |
          echo "VERSION: $VERSION"
          echo "TARGET: $TARGET"
          echo "ARTIFACT_NAME: $ARTIFACT_NAME"
          echo "GH_PAT present: ${{ secrets.GH_PAT != '' }}"
          echo "SPN present: ${{ secrets.dyvenix_app1_SPN != '' }}"

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          workflow: ${{ env.BUILD_WORKFLOW_NAME }}
          name: ${{ env.ARTIFACT_NAME }}
          search_artifacts: true
          skip_unpack: false

      - name: Update JSON Values with Secrets
        run: |
          jq '.ApplicationConfig.LogConfig.DbConnectionString = "${{ secrets.LOG_DB_CONN_STR }}"' appsettings.json > tmp.json && mv tmp.json appsettings.json
          jq '.ApplicationConfig.DataConfig.ConnectionString = "${{ secrets.APP_DB_CONN_STR }}"' appsettings.json > tmp.json && mv tmp.json appsettings.json
          cat appsettings.json

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.dyvenix_app1_SPN }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./
